### ISSUE TITLE
Handling Mouse & keyboard cause focusing issue

### ISSUE THREAD

**Issue by MoatazAbdallh** [sutaking/myjs-faq#1]
how i could keep focusing between keyboard key handling and mouse focus as every time this cause interference because if i use key-down navigation the mouse conflict and keep last focus. How i could remove focus from mouse whenever use keyboard.

**Comment by sutaking** [comment]
Hello, Mr.MoatazAbdallh 
There's no option to close mouse-event of focusing, because caph3 have bind `mouseover` & `mouseout` as default.
Maybe you can try not support mouse in your app. :  )
