### ISSUE TITLE
jQuery Caph3 list can not reload

### ISSUE THREAD

**Issue by sutaking** [sutaking/myjs-faq#2]
Hello! Please, help me. I am developing a widget for tizen smart tv. I have a problem with caph list. After change items, reload method does not work. My code:

````javascript
var app_items_global = [];

function initList(items) {

    app_items_global = items;

    $('#apps_list').caphList({

        items: app_items_global,
        template: '<div class="all_app_item bg_3" focusable><img src="<%=item.icon%>"><p><%=item.name%></p></div>',
        containerClass: 'all_apps_list',
        direction: 'vertical',
    });
}

function updateList(items) {

    app_items_global.length = 0;
    app_items_global = items;
    $("#apps_list")[0].caphList.reload();

}
````

Thank you!
--

**Comment by sutaking** [comment]
Hi, 
Thank for your message~
There're two points you need check.
1. You need have init data to list items.
2. You can not assign new data with '='
 
Because Javascirp have shadow copy to Array, 
You need operate Array API to do it, like that:
````javascript
var item = ["itemA", "itemA"];
function updateList(items) {
    app_items_global.push("item");
    $("#apps_list")[0].caphList.reload();
}
````

**Comment by dronja** [comment]
Thank for your answer. Еhe problem really was in Array.
